name = "jlox"
uuid = "d3d901b3-aa43-49b3-b60f-c52c56d272f6"
authors = ["Orestis Ousoultzoglou"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
